=== dctii/airport/src/main/resources/data/airlineStaffSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="airlineStaff" type="AirlineStaff"/>

    <xs:complexType name="AirlineStaff">
        <xs:sequence>
            <xs:element
                    name="airlineStaffMember"
                    type="AirlineStaffMember"
                    minOccurs="0"
                    maxOccurs="unbounded"
            />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AirlineStaffMember">
        <xs:sequence>
            <xs:element name="memberRole" type="xs:string"/>
            <xs:element name="personInfo" type="PersonInfo"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <xs:complexType name="PersonInfo">
        <xs:sequence>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="givenName" type="xs:string"/>
            <xs:element name="middleName" type="xs:string" minOccurs="0"/>
            <xs:element name="birthdate" type="xs:date"/>
            <xs:element name="sex" type="xs:string"/>
            <xs:element name="emailAddresses" type="EmailAddresses"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <xs:complexType name="EmailAddresses">
        <xs:sequence>
            <xs:element
                    name="emailAddress"
                    type="EmailAddress"
                    minOccurs="0"
                    maxOccurs="unbounded"
            />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmailAddress">
        <xs:sequence>
            <xs:element name="emailAddress" type="xs:string"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

</xs:schema>

=== dctii/airport/src/main/resources/data/airlineStaff.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
    LAX Terminals
    https://www.flylax.com/lax%20new-terminal-maps
-->

<airlineStaff
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="airlineStaffSchema.xsd"
>
    <airlineStaffMember id="1">
        <memberRole>Pilot</memberRole>
        <personInfo id="6">
            <surname>Johnson</surname>
            <givenName>Alice</givenName>
            <middleName>Katelyn</middleName>
            <birthdate>1985-11-25</birthdate>
            <sex>F</sex>
            <emailAddresses>
                <emailAddress id="6">
                    <emailAddress>alice_johnson@delta.com</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
    <airlineStaffMember id="2">
        <memberRole>Flight Attendant</memberRole>
        <personInfo id="7">
            <surname>Ericson</surname>
            <givenName>Alexa</givenName>
            <middleName>Corinna</middleName>
            <birthdate>1985-11-25</birthdate>
            <sex>F</sex>
            <emailAddresses>
                <emailAddress id="7">
                    <emailAddress>alexa_ericson@delta.com</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
    <airlineStaffMember id="3">
        <memberRole>Check-in Staff</memberRole>
        <personInfo id="7">
            <surname>Blart</surname>
            <givenName>Paul</givenName>
            <birthdate>1985-11-25</birthdate>
            <sex>M</sex>
            <emailAddresses>
                <emailAddress id="5">
                    <emailAddress>paul_blart@delta.com</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
    <airlineStaffMember id="4">
        <memberRole>Pilot</memberRole>
        <personInfo id="9">
            <surname>Tanaka</surname>
            <givenName>Hiro</givenName>
            <birthdate>1990-06-15</birthdate>
            <sex>M</sex>
            <emailAddresses>
                <emailAddress id="9">
                    <emailAddress>hiro_tanaka@air-japan.co.jp</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
    <airlineStaffMember id="5">
        <memberRole>Flight Attendant</memberRole>
        <personInfo id="8">
            <surname>Kurosawa</surname>
            <givenName>Joy</givenName>
            <birthdate>1985-11-25</birthdate>
            <sex>F</sex>
            <emailAddresses>
                <emailAddress id="8">
                    <emailAddress>joy_kurosawa@air-japan.co.jp</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
    <airlineStaffMember id="6">
        <memberRole>Check-in Staff</memberRole>
        <personInfo id="10">
            <surname>Sato</surname>
            <givenName>Emi</givenName>
            <birthdate>1992-09-30</birthdate>
            <sex>F</sex>
            <emailAddresses>
                <emailAddress id="10">
                    <emailAddress>emi_sato@air-japan.co.jp</emailAddress>
                </emailAddress>
            </emailAddresses>
        </personInfo>
    </airlineStaffMember>
</airlineStaff>
