=== dctii/airport/src/main/resources/data/gatesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="gates" type="Gates"/>

    <xs:complexType name="Gates">
        <xs:sequence>
            <xs:element
                    name="gate"
                    type="Gate"
                    minOccurs="0"
                    maxOccurs="unbounded"
            />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Gate">
        <xs:sequence>
            <xs:element name="gateCode" type="xs:string"/>
            <xs:element name="airportCode" type="xs:string"/>
            <xs:element name="terminalCode" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

</xs:schema>

=== dctii/airport/src/main/resources/data/gates.xml
<?xml version="1.0" encoding="UTF-8" ?>

<gates
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="gatesSchema.xsd"
>
    <!--
        LAX Terminal B (Tom Bradley International Terminal)
        https://www.flylax.com/terminals/terminal-b
        https://www.flylax.com/-/media/flylax/terminal-map-files/tbit.ashx
    -->
    <gate id="1">
        <gateCode>130</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="2">
        <gateCode>131</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="3">
        <gateCode>132</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="4">
        <gateCode>133</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="5">
        <gateCode>134</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="6">
        <gateCode>135</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="7">
        <gateCode>136</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="8">
        <gateCode>137</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="9">
        <gateCode>138</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="10">
        <gateCode>139</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="11">
        <gateCode>140</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="12">
        <gateCode>141</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="13">
        <gateCode>142</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="14">
        <gateCode>143</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>

    <gate id="15">
        <gateCode>144</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="16">
        <gateCode>145</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="17">
        <gateCode>146</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="18">
        <gateCode>147</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="19">
        <gateCode>148</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="20">
        <gateCode>149</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="21">
        <gateCode>150</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="22">
        <gateCode>151</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="23">
        <gateCode>152</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="24">
        <gateCode>153</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>

    <gate id="25">
        <gateCode>154</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="26">
        <gateCode>155</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="27">
        <gateCode>156</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="28">
        <gateCode>157</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="29">
        <gateCode>158</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="30">
        <gateCode>159</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="31">
        <gateCode>201A</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="32">
        <gateCode>201B</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="33">
        <gateCode>202</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="34">
        <gateCode>203</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="35">
        <gateCode>204</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>

    <gate id="36">
        <gateCode>205</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="37">
        <gateCode>206</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="38">
        <gateCode>207</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="39">
        <gateCode>208</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="40">
        <gateCode>209A</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="41">
        <gateCode>209B</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="42">
        <gateCode>210A</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="43">
        <gateCode>210B</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="44">
        <gateCode>221</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>
    <gate id="45">
        <gateCode>225</gateCode>
        <airportCode>LAX</airportCode>
        <terminalCode>TBIT</terminalCode>
    </gate>

    <!--  HND  -->
    <gate id="46">
        <gateCode>105</gateCode>
        <airportCode>HND</airportCode>
        <terminalCode>T3</terminalCode>
    </gate>
    <gate id="47">
        <gateCode>106</gateCode>
        <airportCode>HND</airportCode>
        <terminalCode>T3</terminalCode>
    </gate>

    <!--  LHR  -->
    <gate id="48">
        <gateCode>30</gateCode>
        <airportCode>LHR</airportCode>
        <terminalCode>T3</terminalCode>
    </gate>
    <gate id="49">
        <gateCode>31</gateCode>
        <airportCode>LHR</airportCode>
        <terminalCode>T3</terminalCode>
    </gate>
    <gate id="50">
        <gateCode>32</gateCode>
        <airportCode>LHR</airportCode>
        <terminalCode>T3</terminalCode>
    </gate>

    <!--  MSQ  -->
    <gate id="51">
        <gateCode>1</gateCode>
        <airportCode>MSQ</airportCode>
        <terminalCode>T1</terminalCode>
    </gate>
    <gate id="52">
        <gateCode>2</gateCode>
        <airportCode>MSQ</airportCode>
        <terminalCode>T1</terminalCode>
    </gate>
    <gate id="53">
        <gateCode>3</gateCode>
        <airportCode>MSQ</airportCode>
        <terminalCode>T1</terminalCode>
    </gate>
</gates>
